apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-lab
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: harness-lab
  template:
    metadata:
      labels:
        app: harness-lab
    spec:
      containers:
      - image: annewesley/helloharness:latest
        name: harness-lab
        ports:
        - containerPort: 80